version: '3'
services:
  php:
    #image: php:7.3-apache
    build: .
    volumes:
      - ./www:/var/www/html
    ports: 
         - 4000:80
  db:
    image: mysql:5.7.40
    ports:
      - 4444:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test 